version: '3'
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: git.stabletec.com
    ports:
      - "4080:80"
      - "22:22"
    volumes:
      - GitlabConfig:/etc/gitlab
      - GitlabLogs:/var/log/gitlab
      - GitlabData:/var/opt/gitlab

volumes:
  GitlabConfig:
  GitlabLogs:
  GitlabData:
