version: '3'
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: git.stabletec.com
    ports:
      - "22:22"
    volumes:
      - GitlabConfig:/etc/gitlab
      - GitlabLogs:/var/log/gitlab
      - GitlabData:/var/opt/gitlab
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx:/etc/nginx
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  GitlabConfig:
  GitlabLogs:
  GitlabData:
