# To setup cert from Let's Encrypt, call
# sudo podman run -it --rm --name certbot -v "/home/ec2-user/etc-letsencrypt:/etc/letsencrypt" -v "/home/ec2-user/var-lib-letsencrypt:/var/lib/letsencrypt" -p 80:80 -p 443:443 docker.io/certbot/certbot:latest certonly

version: '3'
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: git.stabletec.com
    ports:
      - "22:22"
    volumes:
      - GitlabConfig:/etc/gitlab
      - GitlabLogs:/var/log/gitlab
      - GitlabData:/var/opt/gitlab
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf.d:/etc/nginx/conf.d
      - /home/ec2-user/etc-letsencrypt:/etc/letsencrypt
      - /home/ec2-user/var-lib-letsencrypt:/var/lib/letsencrypt

volumes:
  GitlabConfig:
  GitlabLogs:
  GitlabData:
